### ISSUE TITLE
2024年12月1日开始，页面格式变了，文件名也变成了随机

### ISSUE THREAD

**Issue by i6henl** [raddyfiy/The-Peoples-Daily-download#4]
页面：http://paper.people.com.cn/rmrb/pc/layout/202412/01/node_01.html
PDF: http://paper.people.com.cn/rmrb/pc/attachement/202412/01/a88c898d-2aac-42b0-bfde-b9e96fb6bce8.pdf

**Comment by raddyfiy** [comment]
已修复

**Comment by raddyfiy** [comment]
已修复，问题关闭
